telemetry = false
env = false

[install]
auto = "disable"
exact = true
ignoreScripts = true
peer = false
minimumReleaseAge = 259200
minimumReleaseAgeExcludes = []
linker = "isolated"
hoist = false
saveTextLockfile = true
